### ISSUE TITLE
stateLearner issue

### ISSUE THREAD

**Issue by rajanfeba** [jderuiter/statelearner#10]
Hi,
I use state learner to learn state machine for AnbX protocols. I got a few errors when I tried to use a socket with port 6666. Can anyone help me to solve this problem. If not, can someone tell me the steps I should follow to build the state diagram (eg files, functions etc.)
Thanks
Feba
![Screenshot (20)](https://user-images.githubusercontent.com/65386253/233829493-f4e7c758-b68b-40ae-87aa-aa95d10854ab.png)

**Comment by jderuiter** [comment]
This seems to be the same issue as in #9
