### ISSUE TITLE
How to  use

### ISSUE THREAD

**Issue by IMhappyZzz** [jderuiter/statelearner#2]
Hi,
After reading your paper about fuzzing protocol states, I'm really intrested in your work. Now the tool is built successfully. But when I run the jar, it shows "Invalid number of parameters", Is there any doc or would you please tell me how to use the tool? Thank you!

**Comment by jderuiter** [comment]
You probably did not supply a configuration file. I extended the README a bit to include the usage information. Let me know if you have more questions.
